# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-mongo-adapter}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Piotr Solnica}]
  s.date = %q{2011-09-24}
  s.email = %q{piotr.solnica@gmail.com}
  s.executables = [%q{console}]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION.yml",
    "dm-mongo-adapter.gemspec",
    "lib/dm-mongo-adapter.rb",
    "lib/dm-mongo-adapter/adapter.rb",
    "lib/dm-mongo-adapter/aggregates.rb",
    "lib/dm-mongo-adapter/migrations.rb",
    "lib/dm-mongo-adapter/model.rb",
    "lib/dm-mongo-adapter/modifier.rb",
    "lib/dm-mongo-adapter/property/array.rb",
    "lib/dm-mongo-adapter/property/bson_object_id.rb",
    "lib/dm-mongo-adapter/property/foreign_object_id.rb",
    "lib/dm-mongo-adapter/property/hash.rb",
    "lib/dm-mongo-adapter/property/object_id.rb",
    "lib/dm-mongo-adapter/query.rb",
    "lib/dm-mongo-adapter/query/java_script.rb",
    "lib/dm-mongo-adapter/rails/storage.rb",
    "lib/dm-mongo-adapter/resource.rb",
    "lib/dm-mongo-adapter/spec/setup.rb",
    "lib/dm-mongo-adapter/support/class.rb",
    "lib/dm-mongo-adapter/support/date.rb",
    "lib/dm-mongo-adapter/support/date_time.rb",
    "lib/dm-mongo-adapter/support/object.rb",
    "script/performance.rb",
    "spec/integration/adapter_spec.rb",
    "spec/integration/aggregates_spec.rb",
    "spec/integration/associations_spec.rb",
    "spec/integration/model_spec.rb",
    "spec/integration/modifier_spec.rb",
    "spec/integration/properties/foreign_object_id_spec.rb",
    "spec/integration/properties/object_id_spec.rb",
    "spec/integration/property_spec.rb",
    "spec/integration/replica_set_connections_spec.rb",
    "spec/integration/resource_spec.rb",
    "spec/integration/sti_spec.rb",
    "spec/lib/cleanup_models.rb",
    "spec/lib/connection_helper.rb",
    "spec/lib/connection_management.rb",
    "spec/lib/mongod_helper.rb",
    "spec/lib/process_helper.rb",
    "spec/lib/replica_set_helper.rb",
    "spec/lib/replica_set_management.rb",
    "spec/lib/reset_helper.rb",
    "spec/rcov.opts",
    "spec/shared/object_id_type.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/unit/date_time/class_methods/to_mongo_spec.rb",
    "spec/unit/dm-mongo-adapter/adapter/class_methods/new_spec.rb",
    "spec/unit/dm-mongo-adapter/adapter/close_connection_spec.rb",
    "spec/unit/dm-mongo-adapter/adapter/connection_spec.rb",
    "spec/unit/dm-mongo-adapter/model/const_missing_spec.rb",
    "spec/unit/dm-mongo-adapter/property/foreign_object_id_spec.rb",
    "spec/unit/dm-mongo-adapter/property/object_id_spec.rb",
    "tasks/spec.rake",
    "tasks/yard.rake",
    "tasks/yardstick.rake"
  ]
  s.homepage = %q{http://github.com/solnic/dm-mongo-adapter}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{MongoDB DataMapper Adapter}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bson_ext>, ["~> 1.4.0"])
      s.add_runtime_dependency(%q<mongo>, ["~> 1.4.0"])
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.2.0.rc2"])
      s.add_runtime_dependency(%q<dm-migrations>, ["~> 1.2.0.rc2"])
      s.add_runtime_dependency(%q<dm-aggregates>, ["~> 1.2.0.rc2"])
      s.add_development_dependency(%q<dm-annoing-modificators>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.1"])
    else
      s.add_dependency(%q<bson_ext>, ["~> 1.4.0"])
      s.add_dependency(%q<mongo>, ["~> 1.4.0"])
      s.add_dependency(%q<dm-core>, ["~> 1.2.0.rc2"])
      s.add_dependency(%q<dm-migrations>, ["~> 1.2.0.rc2"])
      s.add_dependency(%q<dm-aggregates>, ["~> 1.2.0.rc2"])
      s.add_dependency(%q<dm-annoing-modificators>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<rspec>, ["~> 1.3.1"])
    end
  else
    s.add_dependency(%q<bson_ext>, ["~> 1.4.0"])
    s.add_dependency(%q<mongo>, ["~> 1.4.0"])
    s.add_dependency(%q<dm-core>, ["~> 1.2.0.rc2"])
    s.add_dependency(%q<dm-migrations>, ["~> 1.2.0.rc2"])
    s.add_dependency(%q<dm-aggregates>, ["~> 1.2.0.rc2"])
    s.add_dependency(%q<dm-annoing-modificators>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<rspec>, ["~> 1.3.1"])
  end
end

